### ISSUE TITLE
Numeric Icons look cut off.

### ISSUE THREAD

**Issue by billCln** [andyvorld/LGSTrayBattery#104] opened 2024-02-13 04:50 UTC
I use MX ergo. 50% numeric icon looks a bit off. 
![00000000](https://github.com/andyvorld/LGSTrayBattery/assets/159865572/d07d30f8-c256-4080-9e56-f6c784513444)

Actually, all numeric icon numbers look a bit off. Mx Ergo only displays 90, 50, and 30 because that's what it is implemented by logitech, so I've only seen these 3 numbers being displayed.  You can see 50% looks like it's cut off.  I use windows 10. I haven't messed with the taskbar scaling. It's at default 100% scaling.

This is not the fault of this app. It's win10's poor implementation of scaling. Win 7 was much better with icons scaling.

I believe this can be fixed by changing the resolution size of the numeric icons. Maybe lower the resolution than what it already is, maybe higher resolution, not sure. This is the only way to fix this IMO. Thanks.

**Comment by tr4npt** [comment] 2024-02-15 14:25
The problem is that the icon being created is 256x256 and Windows is scaling it down to fit on the taskbar.  All of the blank space is getting averaged with the text pixels due to the sampling algorithm, resulting in bad text.  I have a fix for this issue and submitted a pull request.

**Comment by andyvorld** [comment] 2024-02-16 10:18
Duplicate of #103, closing this to move discussion there.

**Closed by andyvorld** 2024-02-16 10:18 UTC
